/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansAvaliadorTrabalho;
import modeloBeans.BeansTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoAvaliadorTrabalho;

/**
 *
 * @author TI-MANUTENÇÃO
 */
public class FormAvaliadorTrabalho extends javax.swing.JFrame {

    private DefaultListModel lista = new DefaultListModel();
    BeansAvaliadorTrabalho mod = new BeansAvaliadorTrabalho();
    DaoAvaliadorTrabalho controlAvalidorTrabalho = new DaoAvaliadorTrabalho();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    String nomePessoa;
    String nomeTrabalho;
 
    /**
     * Creates new form FormVinculacaoAvaliador
     */
    public FormAvaliadorTrabalho() {
        initComponents();
        preencherPessoa();
        preencherTrabalho();
        jComboBoxAvaliadores.setSelectedItem(null);
        jComboBoxTrabalhos.setSelectedItem(null);
        addButton.addActionListener(new Action());
        preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonpesquisar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelTrabalho = new javax.swing.JLabel();
        jComboBoxAvaliadores = new javax.swing.JComboBox<>();
        jLabelAvaliadores = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListVinculacao = new javax.swing.JList<>();
        deleteButton = new javax.swing.JButton();
        jComboBoxTrabalhos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVinculacao = new javax.swing.JTable();
        jLabelCadAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(730, 620));

        jButtonNovo.setText("Novo");
        jButtonNovo.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonNovo.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonpesquisar.setText("Pesquisar");
        jButtonpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpesquisarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelID.setText("ID:");

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelTrabalho.setText("Trabalhos:");

        jComboBoxAvaliadores.setEnabled(false);
        jComboBoxAvaliadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAvaliadoresActionPerformed(evt);
            }
        });

        jLabelAvaliadores.setText("Avaliadores:");

        addButton.setText("Adicionar");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        jListVinculacao.setEnabled(false);
        jScrollPane3.setViewportView(jListVinculacao);

        deleteButton.setText("Remover");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jComboBoxTrabalhos.setEnabled(false);
        jComboBoxTrabalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrabalhosActionPerformed(evt);
            }
        });

        jTableVinculacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVinculacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVinculacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVinculacao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonpesquisar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabelID)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelAvaliadores)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jComboBoxAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTrabalho)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTrabalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAvaliadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAvaliadores))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addGap(30, 30, 30)))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTrabalhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrabalho))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpesquisar))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 730, 610);

        jLabelCadAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadAluno.setText("Vinculação de Avaliadores a Trabalhos");
        getContentPane().add(jLabelCadAluno);
        jLabelCadAluno.setBounds(250, 0, 270, 20);

        setSize(new java.awt.Dimension(766, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void preencherPessoa() {
        conex.conexao();
        conex.executaSQL("select nome from pessoa");

        try {
            conex.rs.first();
            jComboBoxAvaliadores.removeAllItems();
            do {
                jComboBoxAvaliadores.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        conex.desconecta();
    }

    public void preencherTrabalho() {
        conex.conexao();
        conex.executaSQL("select titulo from trabalho");

        try {
            conex.rs.first();
            jComboBoxTrabalhos.removeAllItems();
            do {
                jComboBoxTrabalhos.addItem(conex.rs.getString("titulo"));
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        conex.desconecta();
    }
    public void buscaPessoaNome(int idPessoa) {
        conex.conexao();
        conex.executaSQL("select *from pessoa where idpessoa like'%" + idPessoa + "%'");
        try {
            conex.rs.first();
            nomePessoa = conex.rs.getString("nome");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Pessoa não cadastrada!");
        }
    }
    public void buscaTrabalhoNome(int idTrabalho) {
        conex.conexao();
        conex.executaSQL("select *from trabalho where idtrabalho like'%" + idTrabalho + "%'");
        try {
            conex.rs.first();
            nomeTrabalho = conex.rs.getString("titulo");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Trabalho não cadastrado!");
        }
    }

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        jComboBoxAvaliadores.setEnabled(true);
        jComboBoxTrabalhos.setEnabled(true);
        jListVinculacao.setEnabled(true);

        jTextFieldID.setText("");
        jComboBoxAvaliadores.setSelectedItem(null);
        jComboBoxTrabalhos.setSelectedItem(null);

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonpesquisar.setEnabled(false);
        preencherTable("select *from avaliador_trabalho");

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jComboBoxTrabalhos.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Escolha o trabalho para prosseguir");
            jComboBoxTrabalhos.requestFocus();
        } else if (jComboBoxAvaliadores.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jComboBoxAvaliadores.requestFocus();
        } else if (flag == 1) {
            mod.setAvaliador((String) jComboBoxAvaliadores.getSelectedItem());
            mod.setTrabalho((String) jComboBoxTrabalhos.getSelectedItem());
            controlAvalidorTrabalho.salvar(mod);

            jTextFieldID.setText("");
            jComboBoxAvaliadores.setSelectedItem(null);
            jComboBoxTrabalhos.setSelectedItem(null);
            jTextFieldPesquisa.setText("");

            jComboBoxAvaliadores.setEnabled(false);
            jComboBoxTrabalhos.setEnabled(false);
            jListVinculacao.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisa.setEnabled(false);
            jButtonpesquisar.setEnabled(false);
            preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

        } else {
            mod.setAvaliador((String) jComboBoxAvaliadores.getSelectedItem());
            mod.setTrabalho((String) jComboBoxTrabalhos.getSelectedItem());
            controlAvalidorTrabalho.EditarVinculação(mod);

            jTextFieldID.setText("");
            jComboBoxAvaliadores.setSelectedItem(null);
            jComboBoxTrabalhos.setSelectedItem(null);
            jTextFieldPesquisa.setText("");

            jComboBoxAvaliadores.setEnabled(false);
            jComboBoxTrabalhos.setEnabled(false);
            jListVinculacao.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisa.setEnabled(false);
            jButtonpesquisar.setEnabled(false);
            preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jComboBoxAvaliadores.setEnabled(!true);
        jComboBoxTrabalhos.setEnabled(!true);
        jListVinculacao.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldID.setText("");
        jComboBoxAvaliadores.setSelectedItem(null);
        jComboBoxTrabalhos.setSelectedItem(null);
        jTextFieldPesquisa.setText("");

        jTextFieldPesquisa.setEnabled(true);
        jButtonpesquisar.setEnabled(true);
        preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setIdVinculacao(Integer.parseInt(jTextFieldID.getText()));
            controlAvalidorTrabalho.ExcluirVinculacao(mod);
            jButtonExcluir.setEnabled(false);
            jTextFieldID.setText("");
            jComboBoxAvaliadores.setSelectedItem(null);
            jComboBoxTrabalhos.setSelectedItem(null);
            jTextFieldPesquisa.setText("");

            jComboBoxAvaliadores.setEnabled(false);
            jComboBoxTrabalhos.setEnabled(false);
            jListVinculacao.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansAvaliadorTrabalho model = controlAvalidorTrabalho.buscaVinculacao(mod);

        jTextFieldID.setText(String.valueOf(model.getIdVinculacao()));
        jComboBoxAvaliadores.setSelectedItem(model.getAvaliador());
        jComboBoxTrabalhos.setSelectedItem(model.getTrabalho());

        jTextFieldID.setText("");
        jComboBoxAvaliadores.setSelectedItem(null);
        jComboBoxTrabalhos.setSelectedItem(null);
        jTextFieldPesquisa.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTable("select * from avaliador_trabalho where idavaliador_trabalho like'%" + mod.getPesquisa() + "%' order by idavaliador_trabalho");
    }//GEN-LAST:event_jButtonpesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;
        jComboBoxAvaliadores.setEnabled(true);
        jComboBoxTrabalhos.setEnabled(true);
        jListVinculacao.setEnabled(true);

        jComboBoxAvaliadores.setSelectedItem(null);
        jComboBoxTrabalhos.setSelectedItem(null);
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);

        preencherTable("select *from avaliador_trabalho ORDER BY idavaliador_trabalho");

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jComboBoxAvaliadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAvaliadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAvaliadoresActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked

    }//GEN-LAST:event_addButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int indice = jListVinculacao.getSelectedIndex();
        if (indice != -1) {
            lista.remove(indice);
            jListVinculacao.setSelectedIndex(0);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jComboBoxTrabalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrabalhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrabalhosActionPerformed

    private void jTableVinculacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVinculacaoMouseClicked
        // TODO add your handling code here:
        String nome = "" + jTableVinculacao.getValueAt(jTableVinculacao.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSQL("select *from avaliador_trabalho where pessoa_avaliador like'%" + nome + "%'");
        try {
            conex.rs.first();
            jTextFieldID.setText(String.valueOf(conex.rs.getInt("idavaliador_trabalho")));
            buscaPessoaNome(conex.rs.getInt("pessoa_avaliador"));
            jComboBoxAvaliadores.setSelectedItem(nomePessoa);
            buscaTrabalhoNome(conex.rs.getInt("trabalho_avaliar"));
            jComboBoxTrabalhos.setSelectedItem(nomeTrabalho);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados" + ex);
        }
        conex.desconecta();
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTableVinculacaoMouseClicked

    public void preencherTable(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "AVALIADOR", "TRABALHO"};
        conex.conexao();
        conex.executaSQL(sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("idavaliador_trabalho"), conex.rs.getInt("pessoa_avaliador"), conex.rs.getInt("trabalho_avaliar")});
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        BeansTabela modelo = new BeansTabela(dados, colunas);
        jTableVinculacao.setModel(modelo);
        jTableVinculacao.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableVinculacao.getColumnModel().getColumn(0).setResizable(false);
        jTableVinculacao.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableVinculacao.getColumnModel().getColumn(1).setResizable(false);
        jTableVinculacao.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableVinculacao.getColumnModel().getColumn(2).setResizable(false);

        jTableVinculacao.getTableHeader().setReorderingAllowed(false);
        jTableVinculacao.setAutoResizeMode(jTableVinculacao.AUTO_RESIZE_OFF);
        jTableVinculacao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAvaliadorTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAvaliadorTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAvaliadorTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAvaliadorTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAvaliadorTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonpesquisar;
    private javax.swing.JComboBox<String> jComboBoxAvaliadores;
    private javax.swing.JComboBox<String> jComboBoxTrabalhos;
    private javax.swing.JLabel jLabelAvaliadores;
    private javax.swing.JLabel jLabelCadAluno;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTrabalho;
    private javax.swing.JList<String> jListVinculacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableVinculacao;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
class Action implements ActionListener {  //Action

        @Override
        public void actionPerformed(ActionEvent e) {
            lista.addElement(jComboBoxAvaliadores.getSelectedItem());
            jListVinculacao.setModel(lista);//REaction
        }

    }
}
