/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloBeans.BeansAvaliacao;
import modeloBeans.BeansEnumCriterios;
import modeloConection.ConexaoBD;
import modeloDao.DaoAvaliacao;

/**
 *
 * @author TI-MANUTENÇÃO
 */
public class FormAvaliacao extends javax.swing.JFrame {

    BeansAvaliacao mod = new BeansAvaliacao();
    DaoAvaliacao controlAvaliacao = new DaoAvaliacao();
    ConexaoBD conex = new ConexaoBD();
    int codPessoa;
    int flag = 0;

    /**
     * Creates new form FormAvaliacao
     */
    public FormAvaliacao(String usuario) {
        initComponents();
        jLabel1.setText(BeansEnumCriterios.CRITERIO1.getDescricao());
        jLabel2.setText(BeansEnumCriterios.CRITERIO2.getDescricao());
        jLabel3.setText(BeansEnumCriterios.CRITERIO3.getDescricao());
        jLabel4.setText(BeansEnumCriterios.CRITERIO4.getDescricao());
        jLabel5.setText(BeansEnumCriterios.CRITERIO5.getDescricao());
        jLabel6.setText(BeansEnumCriterios.CRITERIO6.getDescricao());
        jLabel7.setText(BeansEnumCriterios.CRITERIO7.getDescricao());
        jLabel8.setText(BeansEnumCriterios.CRITERIO8.getDescricao());
        jLabel9.setText(BeansEnumCriterios.CRITERIO9.getDescricao());
        jLabel10.setText(BeansEnumCriterios.CRITERIO10.getDescricao());
        jLabel11.setText(BeansEnumCriterios.CRITERIO11.getDescricao());
        jLabel12.setText(BeansEnumCriterios.CRITERIO12.getDescricao());
        jLabel13.setText(BeansEnumCriterios.CRITERIO13.getDescricao());
        jLabelUsuario.setText(usuario);

        preencherTrabalho();
        jComboBoxTrabalho.setSelectedItem(null);
    }

    FormAvaliacao() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void preencherTrabalho() {
        conex.conexao();
        conex.executaSQL("select titulo from trabalho");

        try {
            conex.rs.first();
            jComboBoxTrabalho.removeAllItems();
            do {
                jComboBoxTrabalho.addItem(conex.rs.getString("titulo"));
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        conex.desconecta();
    }
    public void buscaOrientadorNome(String login) {
        conex.conexao();
        conex.executaSQL("select *from pessoa where login like'%" + login+ "%'");
        try {
            conex.rs.first();
            codPessoa = conex.rs.getInt("idpessoa");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Pessoa não cadastrada!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jComboBoxTrabalho = new javax.swing.JComboBox<>();
        jLabelAvaliadores = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonpenalizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        jTextFieldNotaCri3 = new javax.swing.JTextField();
        jTextFieldNotaCri7 = new javax.swing.JTextField();
        jTextFieldNotaCri15 = new javax.swing.JTextField();
        jTextFieldNotaCri11 = new javax.swing.JTextField();
        jTextFieldNotaCri16 = new javax.swing.JTextField();
        jTextFieldNotaCri9 = new javax.swing.JTextField();
        jTextFieldNotaCri4 = new javax.swing.JTextField();
        jTextFieldNotaCri6 = new javax.swing.JTextField();
        jTextFieldNotaCri8 = new javax.swing.JTextField();
        jTextFieldNotaCri10 = new javax.swing.JTextField();
        jTextFieldNotaCri12 = new javax.swing.JTextField();
        jTextFieldNotaCri2 = new javax.swing.JTextField();
        jTextFieldNotaCri13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelCadAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(730, 620));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelID.setText("ID:");

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jComboBoxTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTrabalhoActionPerformed(evt);
            }
        });

        jLabelAvaliadores.setText("Trabalho:");

        jLabel1.setText("Criterio01:");

        jLabel2.setText("Criterio02:");

        jLabel3.setText("Criterio03:");

        jLabel4.setText("Criterio04:");

        jLabel5.setText("Criterio05:");

        jLabel6.setText("Criterio06:");

        jLabel7.setText("Criterio07:");

        jLabel8.setText("Criterio08:");

        jLabel9.setText("Criterio09:");

        jLabel10.setText("Criterio10:");

        jLabel11.setText("Criterio11:");

        jLabel12.setText("Criterio12:");

        jLabel13.setText("Criterio13:");

        jButtonpenalizar.setText("Penalizar");
        jButtonpenalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpenalizarActionPerformed(evt);
            }
        });

        jLabel14.setText("Data:");

        jLabel15.setText("Período:");

        jComboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        jComboBoxPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriodoActionPerformed(evt);
            }
        });

        jTextFieldNotaCri3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri3ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri7ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri15ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri11ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri16ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri9ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri4ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri6ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri8ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri10ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri12ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri2ActionPerformed(evt);
            }
        });

        jTextFieldNotaCri13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotaCri13ActionPerformed(evt);
            }
        });

        jLabel16.setText("Avaliador:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabelID)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldNotaCri11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNotaCri13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButtonpenalizar)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAvaliadores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 321, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAvaliadores)
                            .addComponent(jComboBoxTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jComboBoxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldNotaCri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldNotaCri4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNotaCri8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNotaCri3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNotaCri16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNotaCri7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNotaCri11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpenalizar))
                .addGap(191, 191, 191))
        );

        jLabelCadAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadAluno.setText("Avaliação de Trabalhos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabelCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        flag = 1;
        if (jComboBoxTrabalho.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Escolha o trabalho para prosseguir");
            jComboBoxTrabalho.requestFocus();
        } else if (jTextFieldNotaCri3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri3.requestFocus();
        } else if (jTextFieldNotaCri2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri2.requestFocus();
        } else if (jTextFieldNotaCri3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri3.requestFocus();
        } else if (jTextFieldNotaCri4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri4.requestFocus();
        } else if (jTextFieldNotaCri7.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri7.requestFocus();
        } else if (jTextFieldNotaCri6.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri6.requestFocus();
        } else if (jTextFieldNotaCri7.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri7.requestFocus();
        } else if (jTextFieldNotaCri8.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri8.requestFocus();
        } else if (jTextFieldNotaCri9.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri9.requestFocus();
        } else if (jTextFieldNotaCri10.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri10.requestFocus();
        } else if (jTextFieldNotaCri11.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri11.requestFocus();
        } else if (jTextFieldNotaCri12.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri12.requestFocus();
        } else if (jTextFieldNotaCri13.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha o avaliador para prosseguir");
            jTextFieldNotaCri13.requestFocus();
        } else if (flag == 1) {
           
            mod.setAvaliador(jLabelUsuario.getText());
            mod.setTrabalho((String) jComboBoxTrabalho.getSelectedItem());
            mod.setNota1(jTextFieldNotaCri3.getText());
            mod.setNota2(jTextFieldNotaCri2.getText());
            mod.setNota3((String) jTextFieldNotaCri3.getText());
            mod.setNota4((String) jTextFieldNotaCri4.getText());
            mod.setNota5((String) jTextFieldNotaCri7.getText());
            mod.setNota6((String) jTextFieldNotaCri6.getText());
            mod.setNota7((String) jTextFieldNotaCri7.getText());
            mod.setNota8((String) jTextFieldNotaCri8.getText());
            mod.setNota9((String) jTextFieldNotaCri9.getText());
            mod.setNota10((String) jTextFieldNotaCri10.getText());
            mod.setNota11((String) jTextFieldNotaCri11.getText());
            mod.setNota12((String) jTextFieldNotaCri12.getText());
            mod.setNota13((String) jTextFieldNotaCri13.getText());
            mod.setDt(jDateChooser1.getDate());
            mod.setPeriodo((String) jComboBoxPeriodo.getSelectedItem());

            controlAvaliacao.salvar(mod);

            jTextFieldID.setText("");
            jComboBoxTrabalho.setSelectedItem(null);
            jComboBoxPeriodo.setSelectedItem(null);
            jDateChooser1.setDate(null);
            jTextFieldNotaCri3.setText("");
            jTextFieldNotaCri2.setText("");
            jTextFieldNotaCri3.setText("");
            jTextFieldNotaCri4.setText("");
            jTextFieldNotaCri7.setText("");
            jTextFieldNotaCri6.setText("");
            jTextFieldNotaCri7.setText("");
            jTextFieldNotaCri8.setText("");
            jTextFieldNotaCri9.setText("");
            jTextFieldNotaCri10.setText("");
            jTextFieldNotaCri11.setText("");
            jTextFieldNotaCri12.setText("");
            jTextFieldNotaCri13.setText("");

            jComboBoxTrabalho.setEnabled(false);
            jTextFieldNotaCri3.setEnabled(false);
            jTextFieldNotaCri2.setEnabled(false);
            jTextFieldNotaCri3.setEnabled(false);
            jTextFieldNotaCri4.setEnabled(false);
            jTextFieldNotaCri7.setEnabled(false);
            jTextFieldNotaCri6.setEnabled(false);
            jTextFieldNotaCri7.setEnabled(false);
            jTextFieldNotaCri8.setEnabled(false);
            jTextFieldNotaCri9.setEnabled(false);
            jTextFieldNotaCri10.setEnabled(false);
            jTextFieldNotaCri11.setEnabled(false);
            jTextFieldNotaCri12.setEnabled(false);
            jTextFieldNotaCri13.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonpenalizar.setEnabled(false);
            jButtonCancelar.setEnabled(true);

        
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jComboBoxTrabalho.setEnabled(!true);
        jComboBoxPeriodo.setEnabled(!true);
        jDateChooser1.setEnabled(!true);
        jTextFieldNotaCri3.setEnabled(!true);
        jTextFieldNotaCri2.setEnabled(!true);
        jTextFieldNotaCri3.setEnabled(!true);
        jTextFieldNotaCri4.setEnabled(!true);
        jTextFieldNotaCri7.setEnabled(!true);
        jTextFieldNotaCri6.setEnabled(!true);
        jTextFieldNotaCri7.setEnabled(!true);
        jTextFieldNotaCri8.setEnabled(!true);
        jTextFieldNotaCri9.setEnabled(!true);
        jTextFieldNotaCri10.setEnabled(!true);
        jTextFieldNotaCri11.setEnabled(!true);
        jTextFieldNotaCri12.setEnabled(!true);
        jTextFieldNotaCri13.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);

         jTextFieldID.setText("");
            jComboBoxTrabalho.setSelectedItem(null);
            jComboBoxPeriodo.setSelectedItem(null);
            jDateChooser1.setDate(null);
            jTextFieldNotaCri3.setText("");
            jTextFieldNotaCri2.setText("");
            jTextFieldNotaCri3.setText("");
            jTextFieldNotaCri4.setText("");
            jTextFieldNotaCri7.setText("");
            jTextFieldNotaCri6.setText("");
            jTextFieldNotaCri7.setText("");
            jTextFieldNotaCri8.setText("");
            jTextFieldNotaCri9.setText("");
            jTextFieldNotaCri10.setText("");
            jTextFieldNotaCri11.setText("");
            jTextFieldNotaCri12.setText("");
            jTextFieldNotaCri13.setText("");
        dispose();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jComboBoxTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTrabalhoActionPerformed

    private void jButtonpenalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpenalizarActionPerformed
        // TODO add your handling code here:
        FormPenalizacao telaPenalizacao = new FormPenalizacao();
        telaPenalizacao.setVisible(true);
    }//GEN-LAST:event_jButtonpenalizarActionPerformed

    private void jComboBoxPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeriodoActionPerformed

    private void jTextFieldNotaCri3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri3ActionPerformed

    private void jTextFieldNotaCri7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri7ActionPerformed

    private void jTextFieldNotaCri15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri15ActionPerformed

    private void jTextFieldNotaCri11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri11ActionPerformed

    private void jTextFieldNotaCri16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri16ActionPerformed

    private void jTextFieldNotaCri9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri9ActionPerformed

    private void jTextFieldNotaCri4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri4ActionPerformed

    private void jTextFieldNotaCri6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri6ActionPerformed

    private void jTextFieldNotaCri8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri8ActionPerformed

    private void jTextFieldNotaCri10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri10ActionPerformed

    private void jTextFieldNotaCri12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri12ActionPerformed

    private void jTextFieldNotaCri2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri2ActionPerformed

    private void jTextFieldNotaCri13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotaCri13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotaCri13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAvaliacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonpenalizar;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JComboBox<String> jComboBoxTrabalho;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAvaliadores;
    private javax.swing.JLabel jLabelCadAluno;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNotaCri10;
    private javax.swing.JTextField jTextFieldNotaCri11;
    private javax.swing.JTextField jTextFieldNotaCri12;
    private javax.swing.JTextField jTextFieldNotaCri13;
    private javax.swing.JTextField jTextFieldNotaCri15;
    private javax.swing.JTextField jTextFieldNotaCri16;
    private javax.swing.JTextField jTextFieldNotaCri2;
    private javax.swing.JTextField jTextFieldNotaCri3;
    private javax.swing.JTextField jTextFieldNotaCri4;
    private javax.swing.JTextField jTextFieldNotaCri6;
    private javax.swing.JTextField jTextFieldNotaCri7;
    private javax.swing.JTextField jTextFieldNotaCri8;
    private javax.swing.JTextField jTextFieldNotaCri9;
    // End of variables declaration//GEN-END:variables
}
