/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modeloBeans.BeansTrabalho;
import modeloConection.ConexaoBD;
import modeloDao.DaoAluno;
import modeloDao.DaoTrabalho;

/**
 *
 * @author TI-MANUTENÇÃO
 */
public class FormPenalizacao extends javax.swing.JFrame {

    BeansTrabalho mod = new BeansTrabalho();
    DaoTrabalho control = new DaoTrabalho();
    DaoAluno controlAluno = new DaoAluno();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;

    /**
     * Creates new form FormPenalizacao
     */
    public FormPenalizacao() {
        initComponents();
        preencherAluno();
        preencherEvento();
        jComboBoxAlunoLider.setSelectedItem(null);
        jComboBoxIntegrantes.setSelectedItem(null);
        jComboBoxEvento.setSelectedItem(null);
    }

    public void preencherAluno() {
        conex.conexao();
        conex.executaSQL("select nome from aluno");

        try {
            conex.rs.first();
            jComboBoxAlunoLider.removeAllItems();
            do {
                jComboBoxAlunoLider.addItem(conex.rs.getString("nome"));
                jComboBoxIntegrantes.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        conex.desconecta();
    }
    public void preencherEvento() {
        conex.conexao();
        conex.executaSQL("select nome from evento");

        try {
            conex.rs.first();
            jComboBoxEvento.removeAllItems();
            do {
                jComboBoxEvento.addItem(conex.rs.getString("nome"));
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento" + e);
        }
        conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelAlunoLider = new javax.swing.JLabel();
        jLabelIntegrantes = new javax.swing.JLabel();
        jComboBoxAlunoLider = new javax.swing.JComboBox<>();
        jComboBoxIntegrantes = new javax.swing.JComboBox<>();
        jLabelCoorientadorEvento = new javax.swing.JLabel();
        jComboBoxEvento = new javax.swing.JComboBox<>();
        jLabelCadPessoa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelID.setText("ID:");

        jLabelTitulo.setText("Razão:");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jLabelAlunoLider.setText("Aluno:");

        jLabelIntegrantes.setText("Integrantes do grupo:");

        jComboBoxAlunoLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlunoLiderActionPerformed(evt);
            }
        });

        jComboBoxIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIntegrantesActionPerformed(evt);
            }
        });

        jLabelCoorientadorEvento.setText("Evento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIntegrantes)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelID)
                    .addComponent(jLabelAlunoLider)
                    .addComponent(jLabelCoorientadorEvento))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 368, Short.MAX_VALUE))
                    .addComponent(jComboBoxAlunoLider, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxIntegrantes, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAlunoLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlunoLider))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIntegrantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoorientadorEvento))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 730, 180);

        jLabelCadPessoa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelCadPessoa.setText("Penalização de Trabalho");
        getContentPane().add(jLabelCadPessoa);
        jLabelCadPessoa.setBounds(270, 0, 200, 30);

        setSize(new java.awt.Dimension(766, 265));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o título para prosseguir");
            jTextFieldTitulo.requestFocus();
        } else if (jComboBoxAlunoLider.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Escolha o aluno líder para prosseguir");
            jComboBoxAlunoLider.requestFocus();
        } else if (jComboBoxEvento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Escolha o orientador para prosseguir");
            jComboBoxEvento.requestFocus();

        } else if (flag == 1) {

            mod.setTitulo(jTextFieldTitulo.getText());
            mod.setAlunoLider((String) jComboBoxAlunoLider.getSelectedItem());
            mod.setListadeIntegrantes((String) jComboBoxIntegrantes.getSelectedItem());
            mod.setEvento((String) jComboBoxEvento.getSelectedItem());
            control.salvar(mod);
            jTextFieldID.setText("");
            jTextFieldTitulo.setText("");
            jComboBoxAlunoLider.setSelectedItem(null);
            jComboBoxIntegrantes.setSelectedItem(null);
            jComboBoxEvento.setSelectedItem(null);

            jTextFieldTitulo.setEnabled(false);
            jComboBoxAlunoLider.setEnabled(false);
            jComboBoxIntegrantes.setEnabled(false);

            jComboBoxEvento.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);

        } else {
            mod.setIdtrabalho(Integer.parseInt(jTextFieldID.getText()));
            mod.setTitulo(jTextFieldTitulo.getText());
            mod.setAlunoLider((String) jComboBoxAlunoLider.getSelectedItem());
            mod.setListadeIntegrantes((String) jComboBoxIntegrantes.getSelectedItem());
            mod.setEvento((String) jComboBoxEvento.getSelectedItem());
            control.EditarPessoa(mod);

            jTextFieldID.setText("");
            jTextFieldTitulo.setText("");
            jComboBoxAlunoLider.setSelectedItem(null);
            jComboBoxIntegrantes.setSelectedItem(null);

            jComboBoxEvento.setSelectedItem(null);

            jTextFieldTitulo.setEnabled(false);
            jComboBoxAlunoLider.setEnabled(false);
            jComboBoxIntegrantes.setEnabled(false);

            jComboBoxEvento.setEnabled(false);
            jButtonSalvar.setEnabled(false);

            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);

            jButtonCancelar.setEnabled(false);

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldTitulo.setEnabled(!true);
        jComboBoxAlunoLider.setEnabled(!true);
        jComboBoxIntegrantes.setSelectedItem(!true);
        jComboBoxEvento.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);

        jTextFieldID.setText("");
        jTextFieldTitulo.setText("");
        jComboBoxAlunoLider.setSelectedItem(null);
        jComboBoxIntegrantes.setSelectedItem(null);
        jComboBoxEvento.setSelectedItem(null);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jComboBoxAlunoLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlunoLiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlunoLiderActionPerformed

    private void jComboBoxIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIntegrantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIntegrantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenalizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<Object> jComboBoxAlunoLider;
    private javax.swing.JComboBox<String> jComboBoxEvento;
    private javax.swing.JComboBox<Object> jComboBoxIntegrantes;
    private javax.swing.JLabel jLabelAlunoLider;
    private javax.swing.JLabel jLabelCadPessoa;
    private javax.swing.JLabel jLabelCoorientadorEvento;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIntegrantes;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
