/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansEvento;
import modeloBeans.BeansTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoEvento;

/**
 *
 * @author TI-MANUTENÇÃO
 */
public class FormEvento extends javax.swing.JFrame {

    /**
     * Creates new form FormEvento
     */
    BeansEvento mod = new BeansEvento();
    DaoEvento control = new DaoEvento();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;

    public FormEvento() {
        initComponents();
        preencherTable("select *from evento ORDER BY NOME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSiape = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonpesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvento = new javax.swing.JTable();
        jTextFieldID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelConfSenha = new javax.swing.JLabel();
        jLabelConfSenha1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelConfSenha2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCriterio = new javax.swing.JTextField();
        jTextFieldQtMinMenbro = new javax.swing.JTextField();
        jTextFieldQtMinAvalia = new javax.swing.JTextField();
        jTextFieldNotaEvento = new javax.swing.JTextField();
        jTextFieldQtMaxMenbro = new javax.swing.JTextField();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jDateChooserFim = new com.toedter.calendar.JDateChooser();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelInicio = new javax.swing.JLabel();
        jLabelFim = new javax.swing.JLabel();
        jLabelCadAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 610));

        jButtonNovo.setText("Novo");
        jButtonNovo.setMaximumSize(new java.awt.Dimension(75, 23));
        jButtonNovo.setMinimumSize(new java.awt.Dimension(75, 23));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.setMaximumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.setMinimumSize(new java.awt.Dimension(60, 23));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelSiape.setText("Ano:");

        jLabelLogin.setText("Data de Início:");

        jLabelSenha.setText("Data de termino:");

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonpesquisar.setText("Pesquisar");
        jButtonpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpesquisarActionPerformed(evt);
            }
        });

        jTableEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEventoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEvento);

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelID.setText("ID:");

        jLabelConfSenha.setText("Quantidade minima de mebros por trabalho:");

        jLabelConfSenha1.setText("Quantidade maxima de mebros por trabalho:");

        jLabel1.setText("Nota total:");

        jLabelConfSenha2.setText("Quantidade minima de avaliadores por trabalho:");

        jLabel2.setText("Criterio:");

        jTextFieldCriterio.setEnabled(false);

        jTextFieldQtMinMenbro.setEnabled(false);
        jTextFieldQtMinMenbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtMinMenbroActionPerformed(evt);
            }
        });

        jTextFieldQtMinAvalia.setEnabled(false);

        jTextFieldNotaEvento.setEnabled(false);

        jTextFieldQtMaxMenbro.setEnabled(false);

        jDateChooserInicio.setEnabled(false);

        jDateChooserFim.setEnabled(false);

        jTextFieldAno.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonpesquisar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabelID)
                                                    .addComponent(jLabelSiape)
                                                    .addComponent(jLabelNome))
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelConfSenha)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabelConfSenha1))
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldNotaEvento, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldQtMaxMenbro, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldQtMinMenbro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                            .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabelConfSenha2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldQtMinAvalia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelLogin)
                                            .addComponent(jLabelSenha))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooserFim, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFim)
                                            .addComponent(jLabelInicio))
                                        .addGap(127, 127, 127)))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jButtonEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelSiape))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogin)
                                    .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSenha)
                                    .addComponent(jDateChooserFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFim))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtMinMenbro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelConfSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldQtMaxMenbro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNotaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQtMinAvalia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonpesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 730, 610);

        jLabelCadAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadAluno.setText("Cadastro de Eventos");
        getContentPane().add(jLabelCadAluno);
        jLabelCadAluno.setBounds(260, 0, 160, 20);

        setSize(new java.awt.Dimension(766, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jDateChooserFim.setEnabled(true);
        jDateChooserInicio.setEnabled(true);
        jTextFieldQtMinMenbro.setEnabled(true);
        jTextFieldQtMaxMenbro.setEnabled(true);
        jTextFieldNotaEvento.setEnabled(true);
        jTextFieldQtMinAvalia.setEnabled(true);
        jTextFieldCriterio.setEnabled(true);

        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jTextFieldAno.setText("");
        jDateChooserInicio.setDate(null);
        jDateChooserFim.setDate(null);
        jTextFieldQtMinMenbro.setText("");
        jTextFieldQtMaxMenbro.setText("");
        jTextFieldNotaEvento.setText("");
        jTextFieldQtMinAvalia.setText("");
        jTextFieldCriterio.setText("");

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonpesquisar.setEnabled(false);
        preencherTable("select *from evento ORDER BY NOME");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome para prosseguir");
            jTextFieldNome.requestFocus();
        } else if (jTextFieldAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o ano para prosseguir");
            jTextFieldAno.requestFocus();
        } else if (jTextFieldQtMinMenbro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a quantidade minima de integrantes do trabalho para prosseguir");
            jTextFieldQtMinMenbro.requestFocus();
        } else if (flag == 1) {

            mod.setNome(jTextFieldNome.getText());
            mod.setAno(jTextFieldAno.getText());
            mod.setDtInicio(jDateChooserInicio.getDate());
            mod.setDtFim(jDateChooserFim.getDate());
            mod.setQtMinMembro(jTextFieldQtMinMenbro.getText());
            mod.setQtMaxMembro(jTextFieldQtMaxMenbro.getText());
            mod.setNota(jTextFieldNotaEvento.getText());
            mod.setQtMinAvaliador(jTextFieldQtMinAvalia.getText());
            mod.setCriterio(jTextFieldCriterio.getText());
            control.salvar(mod);

            jTextFieldID.setText("");
            jTextFieldNome.setText("");
            jTextFieldAno.setText("");
            jTextFieldQtMinMenbro.setText("");
            jTextFieldQtMaxMenbro.setText("");
            jTextFieldNotaEvento.setText("");
            jTextFieldQtMinAvalia.setText("");
            jTextFieldCriterio.setText("");
            jDateChooserInicio.setDate(null);
            jDateChooserFim.setDate(null);

            jTextFieldNome.setEnabled(false);
            jTextFieldAno.setEnabled(false);
            jDateChooserInicio.setEnabled(false);
            jDateChooserFim.setEnabled(false);
            jTextFieldQtMinMenbro.setEnabled(false);
            jTextFieldQtMaxMenbro.setEnabled(false);
            jTextFieldNotaEvento.setEnabled(false);
            jTextFieldQtMinAvalia.setEnabled(false);
            jTextFieldCriterio.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            preencherTable("select *from evento ORDER BY NOME");

        } else {
            mod.setIdevento(Integer.parseInt(jTextFieldID.getText()));
            mod.setNome(jTextFieldNome.getText());
            mod.setAno(jTextFieldAno.getText());
            mod.setDtInicio(jDateChooserInicio.getDate());
            mod.setDtFim(jDateChooserFim.getDate());
            mod.setQtMinMembro(jTextFieldQtMinMenbro.getText());
            mod.setQtMaxMembro(jTextFieldQtMaxMenbro.getText());
            mod.setNota(jTextFieldNotaEvento.getText());
            mod.setQtMinAvaliador(jTextFieldQtMinAvalia.getText());
            mod.setCriterio(jTextFieldCriterio.getText());
            control.EditarEvento(mod);

            jTextFieldID.setText("");
            jTextFieldNome.setText("");
            jTextFieldAno.setText("");
            jTextFieldQtMinMenbro.setText("");
            jTextFieldQtMaxMenbro.setText("");
            jTextFieldNotaEvento.setText("");
            jTextFieldQtMinAvalia.setText("");
            jTextFieldCriterio.setText("");
            jDateChooserInicio.setDate(null);
            jDateChooserFim.setDate(null);

            jTextFieldNome.setEnabled(false);
            jTextFieldAno.setEnabled(false);
            jDateChooserInicio.setEnabled(false);
            jDateChooserFim.setEnabled(false);
            jTextFieldQtMinMenbro.setEnabled(false);
            jTextFieldQtMaxMenbro.setEnabled(false);
            jTextFieldNotaEvento.setEnabled(false);
            jTextFieldQtMinAvalia.setEnabled(false);
            jTextFieldCriterio.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            preencherTable("select *from evento ORDER BY NOME");

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jDateChooserInicio.setEnabled(true);
        jDateChooserFim.setEnabled(true);
        jTextFieldQtMinMenbro.setEnabled(true);
        jTextFieldQtMaxMenbro.setEnabled(true);
        jTextFieldNotaEvento.setEnabled(true);
        jTextFieldQtMinAvalia.setEnabled(true);
        jTextFieldCriterio.setEnabled(true);

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);

        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jTextFieldAno.setText("");
        jTextFieldQtMinMenbro.setText("");
        jTextFieldQtMaxMenbro.setText("");
        jTextFieldNotaEvento.setText("");
        jTextFieldQtMinAvalia.setText("");
        jTextFieldCriterio.setText("");
        jDateChooserInicio.setDate(null);
        jDateChooserFim.setDate(null);

        preencherTable("select *from evento ORDER BY NOME");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(!true);
        jTextFieldAno.setEnabled(!true);
        jDateChooserInicio.setEnabled(!true);
        jDateChooserFim.setEnabled(!true);
        jTextFieldQtMinMenbro.setEnabled(!true);
        jTextFieldQtMaxMenbro.setEnabled(!true);
        jTextFieldNotaEvento.setEnabled(!true);
        jTextFieldQtMinAvalia.setEnabled(!true);
        jTextFieldCriterio.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);

        jButtonExcluir.setEnabled(false);
        jTextFieldID.setText("");
        jTextFieldNome.setText("");
        jTextFieldAno.setText("");
        jDateChooserInicio.setDate(null);
        jDateChooserFim.setDate(null);
        jTextFieldQtMinMenbro.setText("");
        jTextFieldQtMaxMenbro.setText("");
        jTextFieldNotaEvento.setText("");
        jTextFieldQtMinAvalia.setText("");
        jTextFieldCriterio.setText("");

        jTextFieldPesquisa.setEnabled(true);
        jButtonpesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setIdevento(Integer.parseInt(jTextFieldID.getText()));
            control.ExcluirEvento(mod);
            jButtonExcluir.setEnabled(false);
            jTextFieldID.setText("");
            jTextFieldNome.setText("");
            jTextFieldAno.setText("");
            jTextFieldQtMinMenbro.setText("");
            jTextFieldQtMaxMenbro.setText("");
            jTextFieldNotaEvento.setText("");
            jTextFieldQtMinAvalia.setText("");
            jTextFieldCriterio.setText("");
            jDateChooserInicio.setDate(null);
            jDateChooserFim.setDate(null);

            jTextFieldNome.setEnabled(false);
            jTextFieldAno.setEnabled(false);
            jDateChooserInicio.setEnabled(false);
            jDateChooserFim.setEnabled(false);
            jTextFieldQtMinMenbro.setEnabled(false);
            jTextFieldQtMaxMenbro.setEnabled(false);
            jTextFieldNotaEvento.setEnabled(false);
            jTextFieldQtMinAvalia.setEnabled(false);
            jTextFieldCriterio.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            preencherTable("select *from evento ORDER BY NOME");

        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansEvento model = control.buscaEvento(mod);

        jTextFieldID.setText(String.valueOf(model.getIdevento()));
        jTextFieldNome.setText(model.getNome());
        jTextFieldAno.setText(model.getAno());
        jDateChooserInicio.setDate(model.getDtInicio());
        jDateChooserFim.setDate(model.getDtFim());
        jTextFieldQtMinMenbro.setText(model.getQtMinMembro());
        jTextFieldQtMaxMenbro.setText(model.getQtMaxMembro());
        jTextFieldQtMinAvalia.setText(model.getQtMinAvaliador());
        jTextFieldCriterio.setText(model.getCriterio());

        jTextFieldNome.setEnabled(false);
        jTextFieldAno.setEnabled(false);
        jDateChooserInicio.setEnabled(false);
        jDateChooserFim.setEnabled(false);
        jTextFieldQtMinMenbro.setEnabled(false);
        jTextFieldQtMaxMenbro.setEnabled(false);
        jTextFieldNotaEvento.setEnabled(false);
        jTextFieldQtMinAvalia.setEnabled(false);
        jTextFieldCriterio.setEnabled(false);

        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        preencherTable("select * from evento where nome like'%" + mod.getPesquisa() + "%' order by nome");
    }//GEN-LAST:event_jButtonpesquisarActionPerformed

    private void jTableEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEventoMouseClicked
        // TODO add your handling code here:
        String nome = "" + jTableEvento.getValueAt(jTableEvento.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSQL("select *from evento where nome ='" + nome + "'");
        try {
            conex.rs.first();
            jTextFieldID.setText(String.valueOf(conex.rs.getInt("idevento")));
            jTextFieldNome.setText(conex.rs.getString("nome"));
            jTextFieldAno.setText(conex.rs.getString("ano"));
            jDateChooserInicio.setDate(conex.rs.getDate("dtInicio"));
            jDateChooserFim.setDate(conex.rs.getDate("dtTermino"));
            jTextFieldQtMinMenbro.setText(conex.rs.getString("qtMinMenbro"));
            jTextFieldQtMaxMenbro.setText(conex.rs.getString("qtMaxMenbro"));
            jTextFieldNotaEvento.setText(conex.rs.getString("nota"));
            jTextFieldQtMinAvalia.setText(conex.rs.getString("qtAvaliador"));
            jTextFieldCriterio.setText(conex.rs.getString("criterio"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados");
        }
        conex.desconecta();
        jTextFieldNome.setEnabled(false);
        jTextFieldAno.setEnabled(false);
        jDateChooserInicio.setEnabled(false);
        jDateChooserFim.setEnabled(false);
        jTextFieldQtMinMenbro.setEnabled(false);
        jTextFieldQtMaxMenbro.setEnabled(false);
        jTextFieldNotaEvento.setEnabled(false);
        jTextFieldQtMinAvalia.setEnabled(false);
        jTextFieldCriterio.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTableEventoMouseClicked

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldQtMinMenbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtMinMenbroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtMinMenbroActionPerformed

    public void preencherTable(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "NOME", "ANO", "DTINICIO", "DTTERMINO", "QTMINMENBRO", "QTMAXMENBRO", "NOTA", "QTAVALIADOR", "CRITERIO"};
        conex.conexao();
        conex.executaSQL(sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("idevento"), conex.rs.getString("nome"), conex.rs.getString("ano"),
                    conex.rs.getString("dtInicio"), conex.rs.getString("dtTermino"), conex.rs.getString("qtMinMenbro"), conex.rs.getString("qtMaxMenbro"),
                    conex.rs.getString("nota"), conex.rs.getString("qtAvaliador"), conex.rs.getString("criterio")});
            } while (conex.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o preenchimento");
        }
        BeansTabela modelo = new BeansTabela(dados, colunas);
        jTableEvento.setModel(modelo);
        jTableEvento.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableEvento.getColumnModel().getColumn(0).setResizable(false);
        jTableEvento.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableEvento.getColumnModel().getColumn(1).setResizable(false);
        jTableEvento.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableEvento.getColumnModel().getColumn(2).setResizable(false);
        jTableEvento.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableEvento.getColumnModel().getColumn(3).setResizable(false);
        jTableEvento.getColumnModel().getColumn(4).setPreferredWidth(123);
        jTableEvento.getColumnModel().getColumn(4).setResizable(false);
        jTableEvento.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableEvento.getColumnModel().getColumn(0).setResizable(false);
        jTableEvento.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableEvento.getColumnModel().getColumn(1).setResizable(false);
        jTableEvento.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableEvento.getColumnModel().getColumn(2).setResizable(false);
        jTableEvento.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableEvento.getColumnModel().getColumn(3).setResizable(false);
        jTableEvento.getColumnModel().getColumn(4).setPreferredWidth(123);
        jTableEvento.getColumnModel().getColumn(4).setResizable(false);
        jTableEvento.getTableHeader().setReorderingAllowed(false);
        jTableEvento.setAutoResizeMode(jTableEvento.AUTO_RESIZE_OFF);
        jTableEvento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonpesquisar;
    private com.toedter.calendar.JDateChooser jDateChooserFim;
    private com.toedter.calendar.JDateChooser jDateChooserInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadAluno;
    private javax.swing.JLabel jLabelConfSenha;
    private javax.swing.JLabel jLabelConfSenha1;
    private javax.swing.JLabel jLabelConfSenha2;
    private javax.swing.JLabel jLabelFim;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSiape;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEvento;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCriterio;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNotaEvento;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldQtMaxMenbro;
    private javax.swing.JTextField jTextFieldQtMinAvalia;
    private javax.swing.JTextField jTextFieldQtMinMenbro;
    // End of variables declaration//GEN-END:variables
}
